# Generated by Django 3.1.4 on 2021-05-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iapp', '0002_auto_20210504_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousal',
            name='desc',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
