# Generated by Django 3.1.4 on 2021-05-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iapp', '0003_carousal_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousal',
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
